### ISSUE TITLE
Further fixes beyond my capabilities

### ISSUE THREAD

**Issue by LTLA** [MarioniLab/BarcodeSwapping2017#1]
- [x] Coefficient of determination is missing from Figure 9.
- [x] The text around Figure 20 says "This indicates that the expression abundance of sporadically expressed genes does not drive differences in the swapping fraction estimates." But you're looking at the information score, not the abundance (which you have previously shown to be poorly correlated with the information score).
- [x] Need more detail about "identical pools" in the last paragraph of Section 4.5; I am not sure what this means. Do you mean that one 2500 pool was used in place of the 4000 counts?
- [x] Cite SNN graph people (https://doi.org/10.1093/bioinformatics/btv088)
- [x] Notation for "Experiment 1" in Section 6.2.4 could be better. You're re-using Dataset 1, so call it Dataset 1a and Dataset 1b or something like that. You should also be explicit about how you're using these two libraries as a control for our method; are you trying to detect "swaps" between the two libraries?

**Comment by LTLA** [comment]
__Additional notes for ourselves:__

- No need for Poisson weights in the gene-based model, as all entries would receive the same weight based on the average abundance of the gene.
- The use of the FDR correction for the sharing p-values is probably not appropriate, but the use of the minimum adjusted p-value is equivalent to using Simes' method anyway, which does what we want (tests whether any of the pairs have excess sharing).
- Gene selection based on the information score will probably cause a bit of underestimation of the swapping rate as genes with strong crosshair patterns will be excluded in favour of genes with weak crosshairs (19/96 = 20%, so the 90th percentile will probably be one of the cells in the crosshair).

**Comment by jonathangriffiths** [comment]
These changes have been made. Moreover, considering the 80% vs 90% ratio point, there is not a noticeable difference in the calculated swapping rates as shown in the attached plot (identity line is shown)
[ratio_plot.pdf](https://github.com/MarioniLab/BarcodeSwapping2017/files/1847790/ratio_plot.pdf)
